# This playbook will check for updates and upgrade
# This is tested on Fedora Destro.

---
- hosts: node
  user: root

  tasks:
    - name: check for updates
      raw: /usr/bin/dnf -y update

    - name: upgrade all packages
      raw: /usr/bin/dnf -y upgrade
      
      # you can uncomment the below to do an restart for server/client
        #    - name: reboot system
        #      raw: /usr/sbin/reboot
