---
- hosts: node
  
  
  tasks:

    - name: Remove nginx
      yum:
        name: nginx
        state: absent

    - name: Firewall disabled http
      firewalld:
        permanent: no
        immediate: yes
        service: http
        state: disabled

    - name: firewall disabled https
      firewalld:
        permanent: no
        immediate: yes
        service: https
        state: disabled

    - name: Restart firewall
      systemd:
        name: firewalld
        state: reloaded
